using System.Collections.Generic;

namespace BeatSaberPlaylistToHash.Models
{
    /// <summary>
    /// Represents a beat saber playlist
    /// </summary>
    public class Playlist
    {
        /// <summary>
        /// Gets or sets the title of the playlist
        /// </summary>
        public string PlaylistTitle { get; set; } = "My Playlist";

        /// <summary>
        /// Gets or sets the title of the playlist
        /// </summary>
        public string PlaylistAuthor { get; set; } = "Fuyuki Sakura";

        /// <summary>
        /// Gets or sets the description of the playlist
        /// </summary>
        public string PlaylistDescription { get; set; } = "Generated by Playlist to hash utility";

        /// <summary>
        /// Gets or sets the song list of the playlist
        /// </summary>
        public List<PlaylistSong> Songs { get; set; } = new ();
    }
}
